### PR TITLE
paraletterfreq: first implementation

### LINKED ISSUE #8: Paralell Letter Frequency: Implement basis with first 3-5 suggestions

### PR DESCRIPTION
**Pull request by tehsphinx**
Closes #8

### CODE REVIEW

**Comment by bitfield** [comment]
Looks good; I'll add a PR later with some copyedits on the suggestions. Nice job!

**Comment by bitfield** [comment]
I've seen one or two people used a named function for the goroutine:

```go
go calculateFrequency(s, ch)
```

Probably because they don't know how to use a closure. (I like to ask as a followup question: "Why don't we need to pass the channel into the function? Conversely, why _do_ we need to pass the string in?")

**Comment by bitfield** [comment]
I've also seen someone using a WaitGroup who accidentally called `wg.Wait()` inside the loop, neatly eliminating concurrency!

**Comment by tehsphinx** [comment]
Can you provide a sample of each or just commit them in the `solutions` folder of the `paraletterfreq` exercise?

**Comment by tehsphinx** [comment]
You can also just add the entire test for it:
- add solution in question to new subfolder in `solutions` folder
- add new template to `tpl` folder
- register new template in `tpl/reg.go`
- add a test case in `..._test.go` file with the solution, the registered template and whether the template should be applied or not.

**Comment by bitfield** [comment]
Yes, I'll have a go at this; regrettably, I didn't hang on to the solutions in question, but next time I see one, I'll add it.

**Comment by bitfield** [comment]
I think it's ready for you to look at @tehsphinx!

**Comment by tehsphinx** [comment]
Very nice! Works perfectly!

**Pull request merged**
